apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      enableServiceLinks: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      containers:
      - name: backend
        image: ontology-manager:latest
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 3000

        resources:
          requests:
            memory: "600Mi"
            cpu: "300m"
          limits:
            memory: "600Mi"
            cpu: "600m"

        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            port: http
            path: /api/health

        livenessProbe:
          timeoutSeconds: 5
          httpGet:
            port: http
            path: /api/health

        startupProbe:
          # Give the app about 5min to start
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 5
          httpGet:
            port: http
            path: /api/health

        envFrom:
        - configMapRef:
            name: ontology-manager
            optional: true
        - secretRef:
            name: ontology-manager
            optional: true
