image: docker:latest

services:
- docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

    - mv docker-app-prod/.env.example docker-app-prod/.env

    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -f docker-app-prod/Dockerfile.web .
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
    - tags

deploy1:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack ontology-editor --service editor-zazuko-com --new-image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --upgrade-timeout 600 --wait-for-upgrade-to-finish --rollback-on-error --batch-size 1 --batch-interval 300
  only:
    - tags
