image: docker:latest

services:
- docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sed -i s/example-com/editor/ editor.config.js

    - sed -i s/example-com/editor/ trifid/trifid.config.json
    - sed -i s/example.com/editor.zazuko.com/ trifid/trifid.config.json

    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

    # all the build-arg variables should be set in the env where the build gets executed
    - docker build --pull -t "$CI_REGISTRY_IMAGE/web" --build-arg POSTGRESQL_PASSWORD --build-arg POSTGRESQL_DATABASE --build-arg POSTGRESQL_HOST --build-arg POSTGRAPHILE_TOKEN_SECRET --build-arg POSTGRESQL_POSTGRAPHILE_PASSWORD --build-arg OAUTH_HOST --build-arg OAUTH_CLIENT_ID --build-arg OAUTH_CLIENT_SECRET --build-arg GITHUB_PERSONAL_ACCESS_TOKEN --build-arg EDITOR_HOST -f docker-app-prod/Dockerfile.web .
    - docker push "$CI_REGISTRY_IMAGE/web"
    # spare registry disk space
    # - docker tag "$CI_REGISTRY_IMAGE/web" "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME"
    # - docker push "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME"
    - docker tag "$CI_REGISTRY_IMAGE/web" "$CI_REGISTRY_IMAGE/web:latest"
    - docker push "$CI_REGISTRY_IMAGE/web:latest"
  only:
    - tags

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    # - upgrade --environment default --stack ontology-editor-dev --service web --new-image $CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME
    - upgrade --environment default --stack ontology-editor-dev --service web --new-image $CI_REGISTRY_IMAGE/web:latest
  only:
    - tags
