default:
  image: registry.zazuko.com/docker/deploy-image:v1.4
  tags:
    - kubernetes

stages:
  - build
  - push
  - deploy

# build Docker image
build:
  stage: build

  artifacts:
    paths:
      - image.tar

  script:
    - THEMES="$(mktemp -d)"
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.zazuko.com/docker/ontology-manager-private.git" "$THEMES"
    - rm -rfv "${THEMES}/.git" "${THEMES}"/*.md
    - rsync -avr --out-format="%n" "${THEMES}/" .
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      executor \
        --context="$CI_PROJECT_DIR" \
        --dockerfile=Dockerfile \
        --destination="$CI_REGISTRY_IMAGE" \
        --build-arg="BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg="COMMIT=$CI_COMMIT_SHA" \
        --build-arg="VERSION=$CI_COMMIT_REF_SLUG" \
        --build-arg="SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN" \
        --build-arg="SENTRY_DSN=$SENTRY_DSN" \
        --build-arg="SENTRY_ORG=$SENTRY_ORG" \
        --build-arg="SENTRY_PROJECT=$SENTRY_PROJECT" \
        --build-arg="SENTRY_URL=$SENTRY_URL" \
        --no-push \
        --tarPath="$CI_PROJECT_DIR/image.tar"

# push Docker image
push:
  stage: push

  needs:
    - job: build
      artifacts: true

  variables: # We don't need the sources for that
    GIT_STRATEGY: none

  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - gitlab-docker-push image.tar "$CI_REGISTRY_IMAGE"

# ensure pull-secrets are set for the namespace
deploy:
  stage: deploy
  script:
    - ensure-pull-secret
  environment:
    name: production
    kubernetes:
      namespace: ontology-manager
  only:
    - master
